sudo: required
dist: xenial

language: generic

install:
- sudo apt-add-repository -y ppa:octave/stable
- sudo apt-get update -qq
- sudo apt-get install -qq octave liboctave-dev

env:
  global:
    - MATPOWER_PATH=$TRAVIS_BUILD_DIR/lib:$TRAVIS_BUILD_DIR/lib/t
    - MPTEST_PATH=$TRAVIS_BUILD_DIR/mptest/lib:$TRAVIS_BUILD_DIR/mptest/lib/t
    - MIPS_PATH=$TRAVIS_BUILD_DIR/mips/lib:$TRAVIS_BUILD_DIR/mips/lib/t
    - MOST_PATH=$TRAVIS_BUILD_DIR/most/lib:$TRAVIS_BUILD_DIR/most/lib/t
    - SEARCH_PATH=$MATPOWER_PATH:$MPTEST_PATH:$MIPS_PATH:$MOST_PATH

script:
- octave-cli --no-gui -p $SEARCH_PATH --eval ver
- octave-cli --no-gui -p $SEARCH_PATH --eval mpver
- octave-cli --no-gui -p $SEARCH_PATH --eval "test_mptest(0,1)"
- octave-cli --no-gui -p $SEARCH_PATH --eval "test_mips(0,1)"
- octave-cli --no-gui -p $SEARCH_PATH --eval "test_matpower(0,1)"
- octave-cli --no-gui -p $SEARCH_PATH --eval "test_most(0,1)"
